a=("ritika is don")
print(type(a))
print(a.upper())
print(a.capitalize())
print(a.title())
print(a.find("is"))
print(a.center(50))
print(a.count("a"))
print(a.split(" "))
print(len(a))
print(repr(a))
print(a.replace("don","not only don but also gundi"))